name: Build and deploy JAR app to Azure Web App - mountain-api-backend

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'microsoft'

      - name: Build with Maven
        run: mvn clean install
        working-directory: mountain-backend

      - name: Upload artifact for deployment
        uses: actions/upload-artifact@v4
        with:
          name: java-app
          path: mountain-backend/target/*.jar

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: java-app

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: c620c93e-d208-4e34-8b89-09523c9128c8
          tenant-id: 6bb41fe4-40a3-4a10-b6cd-38278e78b21a
          subscription-id: 377b2e74-7e3d-4090-bd1e-4378db3ab799

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'mountain-api-backend'
          slot-name: 'Production'
          package: 'mountain-backend/target/*.jar'
